feat: 공통컴포넌트 - header , Modal 생성
Dev-FE-2/toy-project2-team2 pull request #12
Opened 2024-11-27 07:59 UTC by anhyeryeon2

## #️⃣ 이슈 번호

> #6 

## 📝 요약

> header,modal 
- logo,profile png는  assets 폴더에 추가하였습니다. 
- modal은 portal 사용했고 dim클릭으로도 취소가능합니다.
- husky에서 규칙에따라 커밋이 막히는 문제가 있어서 경고만 표시하고 커밋은 허용되게 수정하였습니다.'
- 

## 💬 리뷰어에게 공유사항 (선택)
@mgYang53  theme.ts 아래에 만들어주신 함수 이렇게 사용하는게 맞나요..???

## 📸 스크린샷 (선택)
![image](https://github.com/user-attachments/assets/7d623847-8bcc-4d77-b26c-be48b1c21f5a)
![image](https://github.com/user-attachments/assets/7c2bb75c-f157-4842-8843-7a0d76d0dadf)

2024-11-27 09:56 UTC, mgYang53 commented on src/components/common/Header/Header.styled.ts
> +		ont-weight: ${getFontWeight("bold")};
font-weight 오타 발견했습니다 :)

2024-11-27 09:57 UTC, mgYang53 requested changes
오타 난 부분 외에는 괜찮은 것 같아요!
수정해서 다시 푸시 부탁드려요~

2024-11-27 12:09 UTC, anhyeryeon2 commented on src/components/common/Header/Header.styled.ts
> +		ont-weight: ${getFontWeight("bold")};
오오 대박 감사합니당👍👍

2024-11-27 12:39 UTC, mgYang53 approved these changes
👍

2024-11-28 01:43 UTC, park-chan-hui approved these changes

2024-11-28 01:48 UTC, merged