feat: 급여내역 조회 페이지 마크업
Dev-FE-2/toy-project2-team2 pull request #29
Opened 2024-12-04 05:46 UTC by anhyeryeon2

## #️⃣ 이슈 번호

> #21 

## 📝 요약

- 급여내역조회 페이지 마크업 
- 급여 관련 네이밍은` pay보다 salary`가 더 직관적일 것 같아서 전체적으로 수정하였습니다
  
  | **페이지**           | **경로**          |
  |----------------------|--------------------|
  | 급여 조회 페이지     | `/salary`             |
  | 급여 정정 신청 페이지 | `/salary-correction`  |

- 공통컴포넌트 타입  src/types/components 에 분리
- 레이아웃 수정 

## 💬 리뷰어에게 공유사항 (선택)
폴더구조 맞는지 확인 부탁드립니다 !!!! 
그리고 ㅠㅠ 디자인이 아무래도.......한눈에 안들오네요...
섹션별로 컴포넌트 분리한거라,  배치만 살짝 바꿔봤는데..  의견 코멘트 부탁드립니다.....
(현재 pr은 전자 입니다)
## 📸 스크린샷 (선택)
![image](https://github.com/user-attachments/assets/9ffde207-2ac4-442a-8938-34cd80d707e0)

![image](https://github.com/user-attachments/assets/cde20870-d0db-47f0-8a77-5b452011fcbb)

2024-12-04 08:40 UTC, park-chan-hui approved these changes, later dismissed

2024-12-04 08:53 UTC, mgYang53 commented on src/layouts/main/main.styled.ts
padding도 조절하는게 좋긴한데 너무 값을 많이 주면 작은 화면이 될수록 너무 컨텐츠 영역이 좁아질 것 같아요!
그래서 1000px에 컨텐츠를 맞추고 싶으시면 max-width를 1060px로 하고 padding을 0 30px 이런 식으로 적용하면 좋을 것 같습니다!

2024-12-04 09:01 UTC, mgYang53 commented on src/types/components/header.ts
User 타입은 찬희님께서 redux 세팅 이후에 공통으로 만들어서 관리할만한 타입인 것 같네요
redux로 관리되면 이 위치가 아닌 user.ts 같은 파일로 옮겨주는게 좋을 것 같습니다~
@park-chan-hui

2024-12-04 09:04 UTC, mgYang53 requested changes
저는 급여내역 조회 페이지 배치 2단으로 가는 것도 좋은 것 같습니다 👍 
그리고 메인 레이아웃의 max-width와 padding 값만 수정 부탁드립니다!

2024-12-04 09:17 UTC, park-chan-hui commented on src/types/components/header.ts
넵 확인했습니다!

2024-12-04 09:20 UTC, park-chan-hui commented
코멘트를 깜빡했네요 두 번째가 보기 좋은거 같아요!

2024-12-05 03:25 UTC, mgYang53 approved these changes

2024-12-05 05:21 UTC, park-chan-hui approved these changes

2024-12-05 05:22 UTC, merged